### ISSUE TITLE
Implement new layout

### ISSUE THREAD

**Issue by kryptag** [josra/josra.github.io#30]
This is being made only on the main page for now, when we get the look we want ill will make a general layout

this way i don't have to write the same code multiple times.

design on: https://github.com/Praqma/phablework/issues/34

**Comment by kryptag** [comment]
This is first iteration of the new design, and it need to be approved before it will be made into an layout

**Comment by buep** [comment]
I think work can continue in #31 #32 #33 and the one I made I think we need to have as well about how the layout looks and is used. #34
Else I have nothing to "check against" when I'm wondering if something is an error or supposed to be like that.

**Comment by buep** [comment]
I'm okay with the front-page in the current layout.

remove the github stuff in top-right corner.

Twitter is okay with me with transparent white
