### ISSUE TITLE
install Bootstrap locally in the project

### ISSUE THREAD

**Issue by kryptag** [josra/josra.github.io#31]
This is a must to make sure that Bootstrap always will work, because if we use the link and you develop offline or Bootstrap's api is down we wont be affected.

**Comment by kryptag** [comment]
Note to self: i have installed bootstrap and the folder size is 2mb, this is not bad but i might be able to shave this down a bit if needed at a later point @kryptag

**Comment by lakruzz** [comment]
@kryptag 

*I'd really like you to use the phlow when you work the issues!*

There is not commit, tied to this issue - it's really hard to get an idea of what is going on this way.
