### ISSUE TITLE
implement layout that follows the new Wireframe 

### ISSUE THREAD

**Issue by kryptag** [josra/josra.github.io#32]
find desing on: https://github.com/Praqma/phablework/issues/34

**Comment by buep** [comment]
I reconsider, I actually like the grey shade on the side-bar ... would like to have that.

Also the black background behind the logo.

**Comment by kryptag** [comment]
@buep the basic layout is done so i will close this issue, you can find the changes on the branch `32-implement-layout-that-follows-the-new-wireframe`.

**Comment by lakruzz** [comment]
@kryptag 

This is the rule:
Every time you close an issue - you must provide a reference to the commit the implemented the solution.

The Phlow does that automatically - that is why ...You __MUST__ work using the phlow.

pls!
