### ISSUE TITLE
Fix menu - according to layout

### ISSUE THREAD

**Issue by lakruzz** [josra/josra.github.io#41]
#32 was closed with reference to Praqma/phablework#34

Maybe this is related to #33 ?

But they still don't really match

- [x] Menus need to match too

![image](https://user-images.githubusercontent.com/155492/28007579-4375f41e-6554-11e7-96ce-f47d0ef2990e.png)
![image](https://user-images.githubusercontent.com/155492/28007597-4f7a6b96-6554-11e7-841e-7fee6f01e211.png)

- [ ] the size of the sidebar must match the size of the content frame
![image](https://user-images.githubusercontent.com/155492/28007672-959ec57c-6554-11e7-8bda-dc26d82b2a29.png)
![image](https://user-images.githubusercontent.com/155492/28007674-a0e8af4c-6554-11e7-8f4c-c390f57509df.png)

- [x] Something goes really bad on width below 992px and until below 768px

![image](https://user-images.githubusercontent.com/155492/28007893-84036326-6555-11e7-86ec-e2defc902353.png)

![image](https://user-images.githubusercontent.com/155492/28007954-c5937fa6-6555-11e7-8b66-c83dd23a9057.png)

**Comment by kryptag** [comment]
other than the issues addressed here i have added an mobile menu.

**Comment by buep** [comment]
What is next step?

**Comment by kryptag** [comment]
the thing that is needed is to make the sidebar somewhat useful in mobile view, because right now it just disappears. and i need to add the new font and Logo

**Comment by buep** [comment]
And you have an issue on that work?

**Comment by kryptag** [comment]
i will make them this week and groom them so they are ready for the following week

**Comment by buep** [comment]
Okay, I'm just missing a the overall picture of how close we are to going live with new codealliace website so I need issues on all the work needed to go live with new code-alliance website.

I have not overview - we need that.

**Comment by buep** [comment]
according to the list of issues in this repository we're done... you closed this issues, and there is no new so I can go live now?
